"Hello world sample, please remove"
type HelloWorldManagementReport{
  "text"
  sn: String!  
}

type ManagementReportSummaryUser {
  username: String
  count: Int,
  days: Int
  value: Int
}

type ManagementReportSummary{
  timestampType: String
  timestamp: BigInt
  type: String
  count: Int
  amountValue: Int
  days: Int,
  users: [ManagementReportSummaryUser]
}



type Query {
  "Hello world sample, please remove"
  getHelloWorldFromManagementReport: HelloWorldManagementReport
  "get report by day "
  managementReportSubscriptionRecharge(
    businessId: String,
    type: String,
    timestampType: String,
    initDate: BigInt!,
    endDate: BigInt!
  ): [ManagementReportSummary]
}

type Subscription {
  "Hello world sample, please remove"
  ManagementReportHelloWorldSubscription: HelloWorldManagementReport  
}