"Hello world sample, please remove"
type HelloWorldManagementReport{
  "text"
  sn: String!  
}

type ManagementReportSummary{
  timestampType: String
  timestamp: BigInt
  count: Int
  amountValue: Int
  days: Int
}

type Query {
  "Hello world sample, please remove"
  getHelloWorldFromManagementReport: HelloWorldManagementReport
  "get report by day "
  managementReportSubscriptionRecharge(
    type: String,
    timestampType: String,
    initDate: BigInt,
    endDate: BigInt
  ): [ManagementReportSummary]
}

type Subscription {
  "Hello world sample, please remove"
  ManagementReportHelloWorldSubscription: HelloWorldManagementReport  
}