"Hello world sample, please remove"
type HelloWorldManagementReport{
  "text"
  sn: String!  
}

type Query {
  "Hello world sample, please remove"
  getHelloWorldFromManagementReport: HelloWorldManagementReport
}

type Subscription {
  "Hello world sample, please remove"
  ManagementReportHelloWorldSubscription: HelloWorldManagementReport  
}