apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: management-report
spec:
  replicas: 1
  selector:
    matchLabels:
      app: management-report
  template:
    metadata:
      labels:
        app: management-report
    spec:      
      containers:
      - image: nebulaetpi/management-report.backend.management-report:0.0.42
        name: management-report
        volumeMounts:
        - name: google-application-credentials
          mountPath: "/etc/GOOGLE_APPLICATION_CREDENTIALS"
          readOnly: true
        resources:
          requests:
            cpu: "50m"
        env:     
        # EVENT STORE CONFIG 
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/GOOGLE_APPLICATION_CREDENTIALS/gcloud-service-key.json  
        - name: EVENT_STORE_BROKER_TYPE
          value: PUBSUB
        - name: EVENT_STORE_BROKER_EVENTS_TOPIC
          value: events
        - name: EVENT_STORE_STORE_TYPE
          value: MONGO
        - name: EVENT_STORE_STORE_URL
          value: mongodb://dbevents-0.dbevents:27017,dbevents-1.dbevents:27017,dbevents-2.dbevents:27017/test?replicaSet=rs0
        - name: EVENT_STORE_STORE_AGGREGATES_DB_NAME
          value: Aggregates
        - name: EVENT_STORE_STORE_EVENTSTORE_DB_NAME
          value: EventStore
        # INTERNAL MONGO DB CONFIG
        - name: MONGODB_URL
          value: mongodb://mana-repo-mongo:27017
        - name: MONGODB_DB_NAME
          value: management-report
        # JWT CONGIF        
        - name: JWT_PUBLIC_KEY
          valueFrom:
            configMapKeyRef:
              name: keycloak-jwt-public-key
              key: jwt_public_key
        # API - EMI-GATEWAY CONFIG
        - name: EMI-GATEWAY_REPLIES_TOPIC_SUBSCRIPTION
          value: emi-gateway-replies-topic-mbe-management-report
        - name: REPLY_TIMEOUT
          value: '2000'
        - name: BROKER_TYPE
          value: PUBSUB
        # RESET LOCK INITIALIZE BACKED
        - name: LOCKVERSION
          value: "12-07-19_1"
        - name: GMT_TO_SERVE
          value: "GMT-5"
        
      volumes:
      - name: google-application-credentials
        secret:
          secretName: google-application-credentials
      